# Generated by Django 3.2.20 on 2024-04-18 12:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic_id', models.IntegerField()),
                ('chapter_name', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('num_chapter', models.IntegerField()),
                ('img_num', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('comic_name', models.CharField(max_length=255)),
                ('chapter_num', models.IntegerField(default=0)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrawlTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_url', models.CharField(max_length=255)),
                ('task_status', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('last_crawl_time', models.DateTimeField(blank=True, null=True)),
                ('next_crawl_time', models.DateTimeField(blank=True, null=True)),
                ('crawl_cyclicity', models.IntegerField(blank=True, default=1440, null=True)),
                ('crawl_flag', models.CharField(blank=True, max_length=255, null=True)),
                ('site_name', models.CharField(max_length=255)),
                ('crawl_num', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'crawl_task',
            },
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='showImg.chapter')),
                ('img_path', models.JSONField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
